# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Liftracker' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Liftracker
  pod 'Fabric'
  pod 'Crashlytics'
  pod 'RealmSwift'
  pod 'SwiftyBeaver'
  pod 'Charts'
  pod 'Charts/Realm'
  pod 'Material', '~> 2.0'
  pod 'Alamofire', '~> 4.3'
  pod 'Runes'
  pod 'Curry'

  target 'LiftrackerTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'Alamofire', '~> 4.3'
    pod 'OHHTTPStubs' # Default subspecs, including support for NSURLSession & JSON etc
    pod 'OHHTTPStubs/Swift'
    
  end

  target 'LiftrackerUITests' do
    inherit! :search_paths
    # Pods for testing
    pod 'Alamofire', '~> 4.3'
    pod 'OHHTTPStubs' # Default subspecs, including support for NSURLSession & JSON etc
    pod 'OHHTTPStubs/Swift'
    
  end

end
