require 'date'
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "1.103.0"

default_platform :ios

platform :ios do
  before_all do
    cocoapods
    set_version_number
  end

  desc "Runs all the tests"
  lane :test do
  	scan(scheme: "Liftracker")
  end

  desc "Crate a build for developer testing, will push to "
  desc "Crashlytics Beta."
  lane :internal do
    scan(scheme: "Liftracker")
    gym(output_name: "Liftracker_Development",
        clean: true,
        include_symbols: true,
        include_bitcode: true,
        scheme: "Liftracker",
        export_method: "adhoc")
    crashlytics
    #pilot

    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)
  end

  desc "Create a build for external testers."
  desc "Automatically uploads to TestFlight and "
  desc "submits for review"
  lane :beta do
      scan(scheme: "Liftracker")
      gym(output_name: "Liftracker_Internal",
          clean: true,
          include_symbols: true,
          include_bitcode: true,
          scheme: "Liftracker",
          export_method: "app-store")
      pilot
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end

  # Helpers
  def set_version_number
      num = DateTime.now.strftime('%s')
      sh "cd .. && echo $(pwd) && agvtool new-version -all #{num}"
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer
